"""
Typed dataclasses for the Binance Futures Trading Bot.
All shared data structures are defined here for type safety.
"""
from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from enum import Enum
from datetime import datetime, UTC


# ─────────────────────────────────────────────────────────────────────────────
# Enums
# ─────────────────────────────────────────────────────────────────────────────

class Side(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"

class OrderType(str, Enum):
    MARKET = "market"
    LIMIT = "limit"
    STOP_MARKET = "stop_market"

class Regime(str, Enum):
    TREND = "trend"
    RANGE = "range"
    VOLATILE = "volatile"

class SignalAction(str, Enum):
    ENTER_LONG = "ENTER_LONG"
    ENTER_SHORT = "ENTER_SHORT"
    EXIT_LONG = "EXIT_LONG"
    EXIT_SHORT = "EXIT_SHORT"
    DCA_ADD = "DCA_ADD"
    GRID_PLACE = "GRID_PLACE"
    HOLD = "HOLD"


# ─────────────────────────────────────────────────────────────────────────────
# Signal & Trade Structures
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class Signal:
    """Signal generated by a strategy."""
    symbol: str
    action: SignalAction
    side: Optional[Side] = None
    price: Optional[float] = None
    amount: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    strategy: str = ""
    confidence: float = 0.0
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))
    meta: Dict[str, Any] = field(default_factory=dict)


@dataclass
class TradeRecord:
    """Record of an executed trade."""
    symbol: str
    side: Side
    entry_price: float
    exit_price: Optional[float] = None
    amount: float = 0.0
    pnl: float = 0.0
    strategy: str = ""
    entry_time: datetime = field(default_factory=lambda: datetime.now(UTC))
    exit_time: Optional[datetime] = None
    fees: float = 0.0


# ─────────────────────────────────────────────────────────────────────────────
# Grid Strategy Types
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class GridLevel:
    """A single level in the grid strategy."""
    price: float
    side: str  # 'buy' or 'sell'
    amount: float
    order_id: Optional[str] = None
    filled: bool = False


@dataclass
class GridState:
    """State of the grid strategy for a symbol."""
    symbol: str
    levels: List[GridLevel] = field(default_factory=list)
    poc: float = 0.0
    vah: float = 0.0
    val: float = 0.0
    is_active: bool = False
    last_rebuild: Optional[datetime] = None


# ─────────────────────────────────────────────────────────────────────────────
# Trend DCA Types
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class DcaLevel:
    """A single DCA level."""
    price: float
    amount: float
    filled: bool = False
    order_id: Optional[str] = None


@dataclass
class TrendPosition:
    """State of a trend-following DCA position."""
    symbol: str
    side: Optional[Side] = None
    entry_price: float = 0.0
    average_price: float = 0.0
    total_amount: float = 0.0
    dca_levels: List[DcaLevel] = field(default_factory=list)
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    is_active: bool = False


# ─────────────────────────────────────────────────────────────────────────────
# Volume Profile
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class VolumeProfile:
    """Volume profile calculation result."""
    poc: float  # Point of Control
    vah: float  # Value Area High
    val: float  # Value Area Low
    bins: List[float] = field(default_factory=list)
    distribution: List[float] = field(default_factory=list)


# ─────────────────────────────────────────────────────────────────────────────
# Risk & Portfolio
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class PortfolioState:
    """Current portfolio state."""
    equity: float = 0.0
    available_balance: float = 0.0
    total_unrealized_pnl: float = 0.0
    daily_pnl: float = 0.0
    positions: Dict[str, TrendPosition] = field(default_factory=dict)
    kill_switch_active: bool = False


@dataclass
class RiskLimits:
    """Risk configuration limits."""
    max_risk_per_trade: float = 0.01  # 1%
    daily_loss_limit: float = 0.02   # 2%
    max_leverage: int = 3
    max_open_positions: int = 5
    max_exposure_pct: float = 0.50   # 50% of equity


# ─────────────────────────────────────────────────────────────────────────────
# Market State (used by strategy router)
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class MarketState:
    """Snapshot of market data for a symbol."""
    symbol: str
    price: float = 0.0
    regime: Regime = Regime.RANGE
    volume_profile: Optional[VolumeProfile] = None
    indicators: Dict[str, float] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))
